// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHr9c-m3ZY3ggi6Px5FZV41QJgNhbH2mY',
    appId: '1:823501592596:web:1a377afc8819051d11ef01',
    messagingSenderId: '823501592596',
    projectId: 'cloud-msg-dcf03',
    authDomain: 'cloud-msg-dcf03.firebaseapp.com',
    storageBucket: 'cloud-msg-dcf03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjTOty9ZlHC4YG47PxAPB8MaX0c317Co',
    appId: '1:823501592596:android:2efa49cda669675011ef01',
    messagingSenderId: '823501592596',
    projectId: 'cloud-msg-dcf03',
    storageBucket: 'cloud-msg-dcf03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkHAhffywcEQwoGlMyLCidHfmAim_uif8',
    appId: '1:823501592596:ios:b2a220f46e032f2511ef01',
    messagingSenderId: '823501592596',
    projectId: 'cloud-msg-dcf03',
    storageBucket: 'cloud-msg-dcf03.firebasestorage.app',
    iosBundleId: 'com.example.examenFlutterU2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkHAhffywcEQwoGlMyLCidHfmAim_uif8',
    appId: '1:823501592596:ios:b2a220f46e032f2511ef01',
    messagingSenderId: '823501592596',
    projectId: 'cloud-msg-dcf03',
    storageBucket: 'cloud-msg-dcf03.firebasestorage.app',
    iosBundleId: 'com.example.examenFlutterU2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHr9c-m3ZY3ggi6Px5FZV41QJgNhbH2mY',
    appId: '1:823501592596:web:637908f800bca78211ef01',
    messagingSenderId: '823501592596',
    projectId: 'cloud-msg-dcf03',
    authDomain: 'cloud-msg-dcf03.firebaseapp.com',
    storageBucket: 'cloud-msg-dcf03.firebasestorage.app',
  );
}
