// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_S2NrG8wiIVTFuW8WJEkPq42waLr8AQ',
    appId: '1:762336484843:web:71bebf4ea7557cb9154dae',
    messagingSenderId: '762336484843',
    projectId: 'test-login-85435',
    authDomain: 'test-login-85435.firebaseapp.com',
    storageBucket: 'test-login-85435.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAciKwkHUrSXpAa-SOLJ87b5Rn-lnB1Zd0',
    appId: '1:762336484843:android:170395614eca4052154dae',
    messagingSenderId: '762336484843',
    projectId: 'test-login-85435',
    storageBucket: 'test-login-85435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEYe44pjU5qDZ3AzNWCdEog2C2aJZyLdI',
    appId: '1:762336484843:ios:6241195e9eaa3421154dae',
    messagingSenderId: '762336484843',
    projectId: 'test-login-85435',
    storageBucket: 'test-login-85435.firebasestorage.app',
    iosBundleId: 'com.example.logintest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEYe44pjU5qDZ3AzNWCdEog2C2aJZyLdI',
    appId: '1:762336484843:ios:6241195e9eaa3421154dae',
    messagingSenderId: '762336484843',
    projectId: 'test-login-85435',
    storageBucket: 'test-login-85435.firebasestorage.app',
    iosBundleId: 'com.example.logintest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ_S2NrG8wiIVTFuW8WJEkPq42waLr8AQ',
    appId: '1:762336484843:web:0a8148c088fbdb00154dae',
    messagingSenderId: '762336484843',
    projectId: 'test-login-85435',
    authDomain: 'test-login-85435.firebaseapp.com',
    storageBucket: 'test-login-85435.firebasestorage.app',
  );
}
